
<h3 style="
background-color:#1e1e1e;
color:#FFD700;
padding:6px 10px;
border-radius:6px;
">
1/ Data Collection
</h3>

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\Youssef\Desktop\DEPI\Data Science Projects\7.Regression A.(2)\Students_Grades_Predictions.csv")


<h3 style="
background-color:#1e1e1e;
color:#FFD700;
padding:6px 10px;
border-radius:6px;
">
2/ Understanding the Data (EDA)
</h3>

In [4]:
df.head()

,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
0,1.0,John,Male,85.0,15.0,78.0,1.0,High,80.0,4.8,59.0,False
1,2.0,Sarah,Female,90.0,20.0,85.0,2.0,Medium,87.0,2.2,70.0,True
2,3.0,Alex,Male,78.0,10.0,65.0,0.0,Low,68.0,4.6,92.0,False
3,4.0,Michael,Male,92.0,25.0,90.0,3.0,High,92.0,2.9,96.0,False
4,5.0,Emma,Female,NaN,18.0,82.0,2.0,Medium,85.0,4.1,97.0,True

⟹duplicated columns and Need Encoding Categorical Features

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   StudentID                  960 non-null    float64
 1   Name                       966 non-null    object
 2   Gender                     952 non-null    object
 3   AttendanceRate             960 non-null    float64
 4   StudyHoursPerWeek          950 non-null    float64
 5   PreviousGrade              967 non-null    float64
 6   ExtracurricularActivities  957 non-null    float64
 7   ParentalSupport            978 non-null    object
 8   FinalGrade                 960 non-null    float64
 9   Study Hours                976 non-null    float64
 10  Attendance (%)             959 non-null    float64
 11  Online Classes Taken       975 non-null    object
dtypes: float64(8), object(4)
memory usage: 93.9+ KB

⟹Missing (Null) Values

In [6]:
df.describe()

,StudentID,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,FinalGrade,Study Hours,Attendance (%)
count,960.000000,960.000000,950.000000,967.000000,957.000000,960.000000,976.000000,959.000000
mean,5416.019792,85.510417,17.630526,77.598759,1.520376,80.030208,2.406967,77.248175
std,2653.748319,7.332125,6.272132,10.006640,1.046439,9.493652,1.620267,19.298148
min,1.000000,70.000000,8.000000,60.000000,0.000000,62.000000,-5.000000,50.000000
25%,3113.500000,82.000000,12.000000,70.000000,1.000000,72.000000,1.200000,63.000000
50%,5396.500000,88.000000,18.000000,78.000000,1.000000,80.000000,2.500000,76.000000
75%,7754.750000,91.000000,22.000000,86.000000,2.000000,88.000000,3.700000,89.000000
max,9998.000000,95.000000,30.000000,90.000000,3.000000,92.000000,5.000000,200.000000

In [7]:
# Define Our Target
y = df['FinalGrade']

In [8]:
X = df.drop('FinalGrade', axis=1)

In [9]:
# Splitting data to train and test using sklearn
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [10]:
X_train = X_train.drop(['StudentID','Name'], axis=1)

In [11]:
X_test = X_test.drop(['StudentID','Name'], axis=1)

In [12]:
X_train.isnull().sum()

Gender                       43
AttendanceRate               34
StudyHoursPerWeek            42
PreviousGrade                25
ExtracurricularActivities    37
ParentalSupport              16
Study Hours                  21
Attendance (%)               31
Online Classes Taken         18
dtype: int64

In [13]:
X_test.isnull().sum()

Gender                        5
AttendanceRate                6
StudyHoursPerWeek             8
PreviousGrade                 8
ExtracurricularActivities     6
ParentalSupport               6
Study Hours                   3
Attendance (%)               10
Online Classes Taken          7
dtype: int64


<h3 style="
background-color:#1e1e1e;
color:#FFD700;
padding:6px 10px;
border-radius:6px;
">
3.1/ Preprocessing on Training data
</h3>

In [14]:
# Define Numerical features in training data
num_cols = X_train.select_dtypes(include=['int64','float64']).columns
print(num_cols)

Index(['AttendanceRate', 'StudyHoursPerWeek', 'PreviousGrade',
       'ExtracurricularActivities', 'Study Hours', 'Attendance (%)'],
      dtype='object')

In [15]:
# Define Categorical features in training data
cat_cols = X_train.select_dtypes(include=['object','bool']).columns
print(cat_cols)

Index(['Gender', 'ParentalSupport', 'Online Classes Taken'], dtype='object')

In [16]:
# Fill Null With mean in numerical features
for col in num_cols:
    X_train[col] = X_train[col].fillna(X_train[col].mean())

In [17]:
# Fill Null With mode in categorical features
for col in cat_cols:
    X_train[col] = X_train[col].fillna(X_train[col].mode()[0])

C:\Users\Youssef\AppData\Local\Temp\ipykernel_14744\674000012.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X_train[col] = X_train[col].fillna(X_train[col].mode()[0])


<h3 style="
background-color:#1e1e1e;
color:#FFD700;
padding:6px 10px;
border-radius:6px;
">
3.2/ Preprocessing on Testing data
</h3>

In [18]:
X_train = X_train.drop(['Study Hours', 'Attendance (%)'], axis=1)

In [19]:
X_test = X_test.drop(['Study Hours', 'Attendance (%)'], axis=1)

In [20]:
# Define Numerical features in testing data
num_cols_test = X_test.select_dtypes(include=['int64','float64']).columns
print(num_cols_test)

Index(['AttendanceRate', 'StudyHoursPerWeek', 'PreviousGrade',
       'ExtracurricularActivities'],
      dtype='object')

In [21]:
# Define Categorical features in testing data
cat_cols_test = X_test.select_dtypes(include=['object','bool']).columns
print(cat_cols_test)

Index(['Gender', 'ParentalSupport', 'Online Classes Taken'], dtype='object')


<h5 style="
background-color:#1e1e1e;
color:#FFD700;
padding:6px 10px;
border-radius:6px;
">
Handling Missing Values
</h5>

In [22]:
# Fill Null With mean in numerical features
for col in num_cols_test:
    X_test[col] = X_test[col].fillna(X_test[col].mean())

In [23]:
# Fill Null With mean in categorical features
for col in cat_cols_test:
    X_test[col] = X_test[col].fillna(X_test[col].mode()[0])

C:\Users\Youssef\AppData\Local\Temp\ipykernel_14744\572772172.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X_test[col] = X_test[col].fillna(X_test[col].mode()[0])

In [24]:
# Checking 
print(X_train.isnull().sum())

Gender                       0
AttendanceRate               0
StudyHoursPerWeek            0
PreviousGrade                0
ExtracurricularActivities    0
ParentalSupport              0
Online Classes Taken         0
dtype: int64

In [25]:
print(X_test.isnull().sum())

Gender                       0
AttendanceRate               0
StudyHoursPerWeek            0
PreviousGrade                0
ExtracurricularActivities    0
ParentalSupport              0
Online Classes Taken         0
dtype: int64

Encoding

<h5 style="
background-color:#1e1e1e;
color:#FFD700;
padding:6px 10px;
border-radius:6px;
">
Step 1: Apply One-Hot Encoding on training data
</h5>

In [26]:
# Convert categorical columns in X_train into numeric using One-Hot Encoding
X_train = pd.get_dummies(X_train, drop_first=True)

<h5 style="
background-color:#1e1e1e;
color:#FFD700;
padding:6px 10px;
border-radius:6px;
">
Step 2: Apply One-Hot Encoding on testing data
</h5>

In [27]:
# Convert categorical columns in X_test into numeric using the same encoding method
X_test = pd.get_dummies(X_test, drop_first=True)


<h5 style="
background-color:#1e1e1e;
color:#FFD700;
padding:6px 10px;
border-radius:6px;
">
Step 3: Align columns between train and test
</h5>

In [28]:
# Align X_train and X_test to have the same columns
# Missing columns in X_test will be filled with 0
X_train, X_test = X_train.align(X_test, join='left', axis=1, fill_value=0)


<h5 style="
background-color:#1e1e1e;
color:#FFD700;
padding:6px 10px;
border-radius:6px;
">
Step 4: Check shapes
</h5>

In [29]:
# Check that both datasets now have the same number of columns
print(X_train.shape)
print(X_test.shape)

(800, 8)
(200, 8)


<h5 style="
background-color:#1e1e1e;
color:#FFD700;
padding:6px 10px;
border-radius:6px;
">
One-Hot Encoding → converts text to numbers /
drop_first=True → avoids dummy variable trap /
align() → ensures same structure for train and test
</h5>


<h5 style="
background-color:#1e1e1e;
color:#FFD700;
padding:6px 10px;
border-radius:6px;
">
Normalization (Scaling)
</h5>

In [31]:
from sklearn.preprocessing import StandardScaler

num_cols = [
    'AttendanceRate',
    'StudyHoursPerWeek',
    'PreviousGrade',
    'ExtracurricularActivities'
]

scaler = StandardScaler()

X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test[num_cols] = scaler.transform(X_test[num_cols])